name: ZAP Full Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://supreme-space-palm-tree-5w4wj7r9g4434rx4-5000.app.github.dev'
          fail_action: false
          cmd_options: '-a'
